#!/usr/bin/env bash

# If running this script via ssh, /usr/libexec/sshd-keygen-wrapper
# needs to be added to 
# System Settings -> Privacy & Security -> Accessibility


osascript -e '
if application id "io.mpv" is running then
    tell application id "io.mpv" to activate
    tell application "System Events" to keystroke "p"
else
    error "mpv not running" number 9000
end if
'

